// <auto-generated />
using GameLibraryApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GameLibraryApp.Migrations
{
    [DbContext(typeof(GamesContext))]
    partial class GamesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GameLibraryApp.Models.Games", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Cost = 25,
                            Genre = "Action RPG",
                            Name = "Cyberpunk",
                            Platform = "Xbox"
                        },
                        new
                        {
                            ID = 2,
                            Cost = 7,
                            Genre = "Adeventure",
                            Name = "Minecraft",
                            Platform = "Mobile"
                        },
                        new
                        {
                            ID = 3,
                            Cost = 0,
                            Genre = "Battle Royale",
                            Name = "Fortnite",
                            Platform = "Playstation"
                        },
                        new
                        {
                            ID = 4,
                            Cost = 60,
                            Genre = "Racing",
                            Name = "Mariokart",
                            Platform = "Nintendo Consoles"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
